language: go
go:
- 1.16
services:
- docker
script:
- make
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/goreleaser.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
env:
  global:
  - TF_ACC=1
  - GO111MODULE=on
