name: CI
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      TF_ACC: "1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup Golang
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
        with:
          go-version-file: go.mod
      - name: Run linter and tests
        run: make
        env:
          AUTH0_DOMAIN: "${{ secrets.AUTH0_DOMAIN }}"
          AUTH0_CLIENT_ID: "${{ secrets.AUTH0_CLIENT_ID }}"
          AUTH0_CLIENT_SECRET: "${{ secrets.AUTH0_CLIENT_SECRET }}"
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Goreleaser
        run: ./scripts/goreleaser.sh
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
