name: CI
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:


jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      TF_ACC: "1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup Golang
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: Run linter and tests
        run: make
        env:
          AUTH0_DOMAIN: "${{ secrets.AUTH0_DOMAIN }}"
          AUTH0_CLIENT_ID: "${{ secrets.AUTH0_CLIENT_ID }}"
          AUTH0_CLIENT_SECRET: "${{ secrets.AUTH0_CLIENT_SECRET }}"
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ build_test ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Goreleaser
        run: ./scripts/goreleaser.sh
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
